name: 'Setup localstack service'
description: 'Download & run localstack container'
inputs:
  # inputs for https://github.com/docker/login-action
  username:
    description: 'Username used to log against the github registry'
    required: false
    default: ${{ github.actor }}
  password:
    description: 'Password or personal access token used to log against the github registry'
    required: false
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - shell: bash
      run: |
            pip install localstack==3.3.0                                # Install LocalStack cli
            # Below image was copied manually from localstack/localstack:2.2 and uploaded to ghcr
            docker pull ghcr.io/project-zot/ci-images/localstack:3.3.0   # Make sure to pull a working version of the image
            localstack start -d                                          # Start LocalStack in the background

            echo "Waiting for LocalStack startup..."                     # Wait 30 seconds for the LocalStack container
            localstack wait -t 30                                        # to become ready before timing out
            echo "Startup complete"

            aws --endpoint-url=http://localhost:4566 s3api create-bucket --bucket zot-storage --region us-east-2 --create-bucket-configuration="{\"LocationConstraint\": \"us-east-2\"}"
      env:
        AWS_ACCESS_KEY_ID: fake
        AWS_SECRET_ACCESS_KEY: fake

    - shell: bash
      run: |
        docker run -d -p 10000:10000 -p 10001:10001 -p 10002:10002 --name azurite \
            -v /tmp/data:/data \
            -e "AZURITE_ACCOUNTS=zot-storage-test:YXp1cml0ZQo=" \
            mcr.microsoft.com/azure-storage/azurite:3.31.0 azurite-blob --blobHost 0.0.0.0


    - shell: bash
      run: |
        sleep 10
        az storage container create --name zot-storage
      env:
        # https://github.com/Azure/Azurite/blob/main/README.md#usage-with-azure-storage-sdks-or-tools
        AZURE_STORAGE_CONNECTION_STRING: DefaultEndpointsProtocol=http;AccountName=zot-storage-test;AccountKey=YXp1cml0ZQo=;BlobEndpoint=http://127.0.0.1:10000/zot-storage-test;
